# Generated by Django 2.1.3 on 2018-11-20 00:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[(0, 'Profesor'), (1, 'Auxiliar'), (2, 'Ayudante'), (3, 'Estudiante')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[(0, 'Abierta'), (1, 'Cerrada'), (2, 'Publicada')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('seccion', models.IntegerField()),
                ('anho', models.DateField()),
                ('semestre', models.CharField(choices=[(0, 'Verano'), (1, 'Otoño'), (2, 'Primavera')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaCoevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateField(default=None)),
                ('respondida', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Equipo')),
                ('id_coevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Coevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p2', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p3', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p4', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p5', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p6', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p7', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p8', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p9', models.CharField(max_length=1100)),
                ('p10', models.CharField(max_length=1100)),
                ('instancia_coevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.InstanciaCoevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='User',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.Usuario')),
            ],
            bases=('demo.usuario',),
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.Usuario')),
            ],
            bases=('demo.usuario',),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coevaluacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Curso'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Curso'),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='curso',
            field=models.ManyToManyField(through='demo.Cargo', to='demo.Curso'),
        ),
        migrations.AddField(
            model_name='instanciacoevaluacion',
            name='evaluado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancia_coevaluacion_evaluado', to='demo.PersonaNatural'),
        ),
        migrations.AddField(
            model_name='instanciacoevaluacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.PersonaNatural'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='integrantes',
            field=models.ManyToManyField(to='demo.PersonaNatural'),
        ),
        migrations.AddField(
            model_name='curso',
            name='integrantes',
            field=models.ManyToManyField(related_name='curso_integrantes', through='demo.Cargo', to='demo.PersonaNatural'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.PersonaNatural'),
        ),
    ]
