# Generated by Django 2.1.3 on 2018-11-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_admin_personanatural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[(0, 'Profesor'), (1, 'Auxiliar'), (2, 'Ayudante'), (3, 'Estudiante')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('seccion', models.IntegerField()),
                ('anho', models.DateField()),
                ('semestre', models.CharField(choices=[(0, 'Verano'), (1, 'Otoño'), (2, 'Primavera')], max_length=1)),
                ('integrantes', models.ManyToManyField(related_name='cursos', through='demo.Cargo', to='demo.PersonaNatural')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Equipo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.PersonaNatural')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='integrantes',
            field=models.ManyToManyField(through='demo.EstudianteEquipo', to='demo.PersonaNatural'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Curso'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.PersonaNatural'),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='curso',
            field=models.ManyToManyField(through='demo.Cargo', to='demo.Curso'),
        ),
    ]
