# Generated by Django 2.1.3 on 2018-11-19 22:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20181116_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[(0, 'Abierta'), (1, 'Cerrada'), (2, 'Publicada')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaCoevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateField(default=None)),
                ('respondida', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Equipo')),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancia_coevaluacion_evaluado', to='demo.PersonaNatural')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.PersonaNatural')),
                ('id_coevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Coevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p2', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p3', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p4', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p5', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p6', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p7', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p8', models.CharField(choices=[(0, '1.0'), (1, '2.0'), (2, '3.0'), (3, '4.0'), (4, '5.0'), (5, '6.0'), (6, '7.0')], max_length=1)),
                ('p9', models.CharField(max_length=1100)),
                ('p10', models.CharField(max_length=1100)),
                ('instancia_coevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.InstanciaCoevaluacion')),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='integrantes',
            field=models.ManyToManyField(related_name='curso_integrantes', through='demo.Cargo', to='demo.PersonaNatural'),
        ),
        migrations.AddField(
            model_name='coevaluacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Curso'),
        ),
    ]
