# Generated by Django 2.1.3 on 2018-11-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciacoevaluacion',
            name='respuesta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.Respuesta'),
        ),
    ]
