# Generated by Django 2.1.3 on 2018-11-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20181115_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.Usuario')),
            ],
            bases=('demo.usuario',),
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.Usuario')),
            ],
            bases=('demo.usuario',),
        ),
    ]
