# Generated by Django 2.1.3 on 2018-11-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20181120_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=1100)),
                ('p2', models.CharField(max_length=1100)),
                ('p3', models.CharField(max_length=1100)),
                ('p4', models.CharField(max_length=1100)),
                ('p5', models.CharField(max_length=1100)),
                ('p6', models.CharField(max_length=1100)),
                ('p7', models.CharField(max_length=1100)),
                ('p8', models.CharField(max_length=1100)),
                ('p9', models.CharField(max_length=1100)),
                ('p10', models.CharField(max_length=1100)),
            ],
        ),
        migrations.AddField(
            model_name='coevaluacion',
            name='preguntas',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coevaluacion', to='demo.Preguntas'),
            preserve_default=False,
        ),
    ]
