# Generated by Django 2.1.1 on 2018-11-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20181120_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
        migrations.AlterField(
            model_name='curso',
            name='anho',
            field=models.IntegerField(),
        ),
    ]
