# Generated by Django 2.1.1 on 2018-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20181122_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(choices=[('0', 'Profesor'), ('1', 'Auxiliar'), ('2', 'Ayudante'), ('3', 'Estudiante')], max_length=1),
        ),
        migrations.AlterField(
            model_name='coevaluacion',
            name='estado',
            field=models.CharField(choices=[('0', 'Abierta'), ('1', 'Cerrada'), ('2', 'Publicada')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestre',
            field=models.CharField(choices=[('0', 'Verano'), ('1', 'Otoño'), ('2', 'Primavera')], max_length=1),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='p1',
            field=models.CharField(choices=[('0', '1.0'), ('1', '2.0'), ('2', '3.0'), ('3', '4.0'), ('4', '5.0'), ('5', '6.0'), ('6', '7.0')], max_length=1),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='p2',
            field=models.CharField(choices=[('0', '1.0'), ('1', '2.0'), ('2', '3.0'), ('3', '4.0'), ('4', '5.0'), ('5', '6.0'), ('6', '7.0')], max_length=1),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='p3',
            field=models.CharField(choices=[('0', '1.0'), ('1', '2.0'), ('2', '3.0'), ('3', '4.0'), ('4', '5.0'), ('5', '6.0'), ('6', '7.0')], max_length=1),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='p4',
            field=models.CharField(choices=[('0', '1.0'), ('1', '2.0'), ('2', '3.0'), ('3', '4.0'), ('4', '5.0'), ('5', '6.0'), ('6', '7.0')], max_length=1),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='p5',
            field=models.CharField(choices=[('0', '1.0'), ('1', '2.0'), ('2', '3.0'), ('3', '4.0'), ('4', '5.0'), ('5', '6.0'), ('6', '7.0')], max_length=1),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='p6',
            field=models.CharField(choices=[('0', '1.0'), ('1', '2.0'), ('2', '3.0'), ('3', '4.0'), ('4', '5.0'), ('5', '6.0'), ('6', '7.0')], max_length=1),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='p7',
            field=models.CharField(choices=[('0', '1.0'), ('1', '2.0'), ('2', '3.0'), ('3', '4.0'), ('4', '5.0'), ('5', '6.0'), ('6', '7.0')], max_length=1),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='p8',
            field=models.CharField(choices=[('0', '1.0'), ('1', '2.0'), ('2', '3.0'), ('3', '4.0'), ('4', '5.0'), ('5', '6.0'), ('6', '7.0')], max_length=1),
        ),
    ]
